### ISSUE TITLE
_RegexParser fails to build with a 5.6 toolchain

### ISSUE THREAD

**Issue by hamishknight** [apple/swift-experimental-string-processing#451]
When doing a `--bootstrapping=hosttools` Swift compiler build with Xcode 13.4, you get the error:

```
/Users/hamish/src/swift-dev/swift-experimental-string-processing/Sources/_RegexParser/Utility/TypeConstruction.swift:63:64: error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate
    let result = elementTypes.withContiguousStorageIfAvailable { elementTypesBuffer in
                                                               ^
                                                                                    -> <#Result#>
```

We should ideally allow _RegexParser to compile with a 5.6 toolchain.
