### PR TITLE
Fix _RegexParser build when using 5.6 host tools

### LINKED ISSUE #451: _RegexParser fails to build with a 5.6 toolchain
When doing a `--bootstrapping=hosttools` Swift compiler build with Xcode 13.4, you get the error:

```
/Users/hamish/src/swift-dev/swift-experimental-string-processing/Sources/_RegexParser/Utility/TypeConstruction.swift:63:64: error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate
    let result = elementTypes.withContiguousStorageIfAvailable { elementTypesBuffer in
                                                               ^
                                                                                    -> <#Result#>
```

We should ideally allow _RegexParser to compile with a 5.6 toolchain.

### PR DESCRIPTION
**Pull request by hamishknight**
Add a type annotation to allow a `--bootstrap=hosttools` compiler build to work with a Swift 5.6 compiler.

Resolves #451

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test
